### ISSUE TITLE
A shameful issue.

### ISSUE THREAD

**Issue by Stevewsw** [WoongheeLee/DeepSleepNet_Implementation_in_Keras#1]
IN the: 

cell 4: 
`myfile = open('../deepsleepnet/data_pickle/eeg_fpz_cz.pretrain','rb')
data = pickle.load(myfile, encoding='bytes')`

cell: 
`myfile = open('../deepsleepnet/data_pickle/eeg_fpz_cz.finetuning','rb')
data2 = pickle.load(myfile, encoding='bytes')`

how can I get the "myfile" that you have used with the type , I cannot download the dataset from the [open source.](https://physionet.org/pn4/sleep-edfx/) at once time. Even I download it one by one, how can I convert it into your 'type'.

It is grateful if this issue would be responsed.

**Comment by WoongheeLee** [comment]
I am sorry. I missed how to prepare the data set.

To thank for original implementation of deepsleepnet(https://github.com/akaraspt/deepsleepnet), I could follow downloading and preparing dataset.

To download and prepare the data set, you can follow the section of "Prepare dataset" of the README.md (https://github.com/akaraspt/deepsleepnet/blob/master/README.md).

Thanks.

**Comment by Stevewsw** [comment]
yep, thanks for your immediately response.

_**Expecting your future work**_, by the way.

[The Sleep-EDF Database](https://www.physionet.org/physiobank/database/sleep-edfx/) updated on 2018-4.  **they expanded the Dataset.** 


**old:** https://physionet.org/pn4/sleep-edfx/
**new:** https://www.physionet.org/physiobank/database/sleep-edfx/
